### ISSUE TITLE
ENH: API/TSLib - Start an evaluation from a list of Model IDs

### ISSUE THREAD

**Issue by weirong-duke** [Striveworks/valor#494]
### Feature Type

- [X] Adding new functionality to valor

- [ ] Changing existing functionality in valor

- [ ] Removing existing functionality in valor

### Problem Description

Currently, the TS client has the ability to start and evaluation from a model and a dataset: https://github.com/Striveworks/valor/blob/1aa85e424c93143c839be2ab1e339036f693eb57/ts-client/src/ValorClient.ts#L244C16-L244C37

With the upcoming evaluations UI, we would like to be able to start an evaluation with a multiple modelIds and a dataset id (but potentially multiple dataset IDs to future-proof)

It seems like the backend already has support for multiple model names, but not model ids: https://github.com/Striveworks/valor/blob/1aa85e424c93143c839be2ab1e339036f693eb57/api/valor_api/crud/_create.py#L89

### Feature Description

Backend API call to `create_or_get` evaluations but with modelId as a parameter. alternatively extend existing `create_or_get`'s job_request Schema 

Additionally, valor ts-client updates in order to support new functionality ^

**Comment by ekorman** [comment]
@weirong-duke fyi model ids aren't client facing and we actually just removed them from the python and ts clients. but we will add bulk support for multiple model names

**Comment by ekorman** [comment]
the other thing to note is that right now the bulk create takes dataset names but that evaluations on the union of the datasets and not evaluating on each one separately, which is what the Chariot integration will want. so if we don't want to do that in multiple calls (one for each dataset) then we would have to change the backend.
