### ISSUE TITLE
Update Filter Schemas + Query Generation

### ISSUE THREAD

**Issue by czaloom** [Striveworks/valor#526]
### Feature Type

- [ ] Adding new functionality to valor

- [X] Changing existing functionality in valor

- [ ] Removing existing functionality in valor

### Problem Description

Filter schemas still using old format.

### Feature Description

Update the filter object to use the JSON schemas introduced in PR #485.

The following python client code should work .

```
# Q: I want overhead images from specific datasets.
f = Dataset.name.in_(["dataset1", "dataset2"])

# Q: I want to constrain to images of swimmers where a boat is also in the image. 
f &= (
    Datum.where(Label.value.in_(["swimmer", "diver"]))
    & Datum.where(Label.value.in_(["boat", "ship"]))
)

# Q: I only want images between 08:00:00 and 18:00:00.
f &= (
    (Datum.metadata["time_of_day"] > datetime.time(hour=8))
    & (Datum.metadata["time_of_day"] < datetime.time(hour=18))
)
```

**Comment by ntlind** [comment]
Includes "Implement ability to filter on groundtruth labels"
