### ISSUE TITLE
ENH: Add details to 'fp' and 'fn' sections in PR curve metrics for no ground truth/prediction or incorrect label

### ISSUE THREAD

**Issue by MattMcClainStrive** [Striveworks/valor#576]
### Feature Type

- [X] Adding new functionality to valor

- [ ] Changing existing functionality in valor

- [ ] Removing existing functionality in valor

### Problem Description

In the PR curve metrics, it would be helpful if the data about false positives ('fp') and false negatives ('fn') included information about whether the error was due to a bad detection (no object there) or a misclassified detection (and if so, the actual label in the ground truth/prediction).

### Feature Description

PR curve metrics include more information about false positives and false negatives.

**Comment by ntlind** [comment]
Agreed on a solution in #582
