### ISSUE TITLE
DOC: Basic Usage doc page seems outdated

### ISSUE THREAD

**Issue by goelakash** [Striveworks/valor#587]
### Location of the documentation

https://striveworks.github.io/valor/basic_usage/

### Documentation problem

There are several issues with the code example in this page. Tried using the code but there are issues with imports and object creation. 

### Suggested fix for documentation

I think the page should either be updated using code from here: https://github.com/Striveworks/valor/blob/main/examples/getting_started.ipynb or simply deprecated.

**Comment by ntlind** [comment]
Thank you for submitting this Issue, @goelakash; we greatly appreciate your feedback! 

We agree that the "Basic Usage" doc was confusing, so we've followed your advice and deprecated it in favor of our "Getting Started" notebook.
