### ISSUE TITLE
ENH: add client request timeout and possibly retry

### ISSUE THREAD

**Issue by rsbowman-striveworks** [Striveworks/valor#610]
### Feature Type

- [ ] Adding new functionality to valor

- [X] Changing existing functionality in valor

- [ ] Removing existing functionality in valor

### Problem Description

Valor client connections can hang.  

### Feature Description

Requests should use a [timeout](https://requests.readthedocs.io/en/stable/user/quickstart/#timeouts).  It's not important for us that the timeout is configurable, it can just be some reasonable value (10s?).  

Since we're adding a timeout, it might be worth adding retries with backoff, at least for idempotent requests.

**Comment by ntlind** [comment]
From Scott: consider [swapping requests with urllib3](https://striveworks.slack.com/archives/C04JJ15357U/p1718118052953219?thread_ts=1718046030.825299&cid=C04JJ15357U)

**Comment by ntlind** [comment]
From Scott: should we consider swapping `requests` with `urllib3`?
