### ISSUE TITLE
BUG: `valor_api.backend.core.label.validate_matching_label_keys` Fails unexpectedly

### ISSUE THREAD

**Issue by czaloom** [Striveworks/valor#640]
### valor version checks

- [X] I have confirmed this bug exists on the latest version of valor.

### Reproducible Example

```python
N/A
```

### Issue Description

- If a dataset exists with similar parameters it can be pulled into the filter causing validation errors.
- Also, why are label values validated in this function?

### Expected Behavior

Should validate that a dataset and model share label keys.

**Comment by ntlind** [comment]
@czaloom please add a reproducible example to re-open this issue
