### ISSUE TITLE
BUG: Valor Core mAP is not calculated correctly when there are predictions for a class, but no ground truths

### ISSUE THREAD

**Issue by jqu-striveworks** [Striveworks/valor#736]
### valor version checks

- [X] I have confirmed this bug exists on the latest version of valor.

### Reproducible Example

```python
from valor_core import detection, schemas

def _images(n) -> list[schemas.Datum]:
    return [
        schemas.Datum(
            uid=f"{i}",
            metadata={
                "height": 1000,
                "width": 2000,
            },
        )
        for i in range(n)
    ]


def evaluate_detection_functional_test_groundtruths(
    images,
) -> list[schemas.GroundTruth]:
    """Creates a dataset called "test_dataset" with some ground truth
    detections. These detections are taken from a torchmetrics unit test (see test_metrics.py)
    """

    gts_per_img = [
        {
            "boxes": [[10, 10, 20, 20]],
            "labels": ["0"],
        },
    ]

    return [
        schemas.GroundTruth(
            datum=image,
            annotations=[
                schemas.Annotation(
                    labels=[schemas.Label(key="class", value=class_label)],
                    bounding_box=schemas.Box.from_extrema(
                        xmin=box[0],
                        ymin=box[1],
                        xmax=box[2],
                        ymax=box[3],
                    ),
                    is_instance=True,
                )
                for box, class_label in zip(gts["boxes"], gts["labels"])
            ],
        )
        for gts, image in zip(gts_per_img, images)
    ]


def evaluate_detection_functional_test_predictions(
    images,
) -> list[schemas.Prediction]:
    """Creates a model called "test_model" with some predicted
    detections on the dataset "test_dataset". These predictions are taken
    from a torchmetrics unit test (see test_metrics.py)
    """

    '''
    preds_per_img = [
        {
            "boxes": [[10, 10, 20, 20]],
            "scores": [1.0],
            "labels": ["0"],
        }
    ]
    '''

    ## This produces the same precision metrics as above
    preds_per_img = [
        {
            "boxes": [[10, 10, 20, 20], [100, 100, 200, 200]],
            "scores": [1.0, 1.0],
            "labels": ["0", "1"],
        }
    ]

    db_preds_per_img = [
        schemas.Prediction(
            datum=image,
            annotations=[
                schemas.Annotation(
                    labels=[
                        schemas.Label(
                            key="class", value=class_label, score=score
                        )
                    ],
                    bounding_box=schemas.Box.from_extrema(
                        xmin=box[0],
                        ymin=box[1],
                        xmax=box[2],
                        ymax=box[3],
                    ),
                    is_instance=True,
                )
                for box, class_label, score in zip(
                    preds["boxes"], preds["labels"], preds["scores"]
                )
            ],
        )
        for preds, image in zip(preds_per_img, images)
    ]

    return db_preds_per_img


imgs = _images(1)
groundtruths = evaluate_detection_functional_test_groundtruths(imgs)
predictions = evaluate_detection_functional_test_predictions(imgs)

metrics_out = detection.evaluate_detection(
    groundtruths=groundtruths,
    predictions=predictions,
)

for i in metrics_out.metrics:
    print(i)
```

### Issue Description

If I have an image that has cats, and I use a Cat-dog detector model on it, the mAP calculation does not take into account the False positive Dog detections. 

Also metrics output a meaningless AR metric for dog.

### Expected Behavior

If I have two models and a cat-only dataset, and one produces perfect cat detections and 0 dog detections, while the other produces perfect cat detections and 1000 dog detections. I would not expect both of the models to have the same precision.

If I have a dataset with cats and one image with only 1 dog, and my model produces perfect cat detections and 1 FP dog detection (in an image without the dog). My model should not suddenly "improve" it's precision if remove that one image of a dog that it never detected.

Perhaps there needs to be an argument to specify the classes to evaluate metrics over. As it stands, simple infering based on the groundtruths and prediction is ambiguous.

**Comment by ntlind** [comment]
Additional context on [slack](https://striveworks.slack.com/archives/C04JJ15357U/p1725475840610939)

**Comment by ntlind** [comment]
there's a few issues being touched on here:

> If I have two models and a cat-only dataset, and one produces perfect cat detections and 0 dog detections, while the other produces perfect cat detections and 1000 dog detections. I would not expect both of the models to have the same precision.

this hypothesis most closely matches the reproducible example. in this case, it comes down to the IOU of the dog detections. in the reproducible example you supplied, the IOU between the groundtruth and the second prediction is 0, so the second prediction is effectively discarded for all AP / AR calculations. this is expected behavior. the `DetailedPrecisionRecallCurve` operates a little differently, and should count that "dog" prediction as a false positive. I've added tests to `lite` to check for this behavior .

> If I have a dataset with cats and one image with only 1 dog, and my model produces perfect cat detections and 1 FP dog detection (in an image without the dog). My model should not suddenly "improve" it's precision if remove that one image of a dog that it never detected.

this issue isn't tested in the reproducible example, but is something we discussed in the aforementioned slack thread. going to move this second topic to be its own issue.
